[build]
rustflags = ["-C" , "target-feature=+crt-static"]
linker = "rust-lld"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true


[profile.release]
opt-level = 3
debug = false
debug-assertions = false


[env]
RUST_BACKTRACE= "full"

